name: Python to Executable on Push

on:
  push:
    paths:
      - '*.py'

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          
      - name: Install PyInstaller
        run: pip install pyinstaller
        
      - name: Create Executables
        run: |
          mkdir dist  # Ensure dist directory exists
          for file in *.py; do
            pyinstaller --onefile --distpath dist --name "${file%.*}" "$file"
          done
        shell: bash

      - name: Upload Executables as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: executables
          path: dist/**
